[phases.setup]
nixPkgs = ["conda"]

[phases.install]
cmds = [
  "conda env create -f backend/environment.yml",
  "source activate analyst-env"
]

[phases.build]
cmds = [
  "source activate analyst-env",
  "cd frontend && npm install",
  "cd frontend && npm run build",
  "mkdir -p backend/static",
  "cp -r frontend/build/* backend/static/"
]

[start]
cmd = "source activate analyst-env && uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT" 