name: analyst-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.25.2
  - pandas=2.1.4
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - psycopg2-binary=2.9.9
  - sqlalchemy=2.0.23  
  - spacy=3.7.2
  - nltk=3.8.1
  - pip:
      - redis==5.0.1
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - alembic==1.12.1
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - python-multipart==0.0.6
      - pydantic==2.5.0
      - pydantic-settings==2.1.0
      - google-generativeai==0.3.2
      - python-dotenv==1.0.0
      - PyPDF2==3.0.1
      - pdfplumber==0.10.3
      - pymupdf==1.23.8
      - langchain==0.1.0
      - chromadb==0.4.18
      - faiss-cpu==1.7.4
      - textstat==0.7.3
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - black==23.11.0
      - flake8==6.1.0
      - email-validator==2.2.0